owner: Whipcode-API
repo: status

sites:
  - name: Whipcode API
    url: $WHIPCODE_BACKEND
    method: POST
    icon: https://av9.dev/whipcode/assets/null.png
  - name: Whipcode Site
    url: https://whipcode.app
    icon: https://av9.dev/whipcode/assets/null.png
  - name: Whipcode Docs
    url: https://docs.whipcode.app
    icon: https://av9.dev/whipcode/assets/null.png
  - name: RapidAPI Proxy
    url: https://whipcode.p.rapidapi.com
    method: POST
    expectedStatusCodes:
      - 200
      - 201
      - 401
    icon: https://av9.dev/whipcode/assets/null.png

status-website:
  introTitle: "**Uptime Monitor**"
  introMessage: "Status page for [Whipcode API](https://whipcode.app)"
  cname: status.whipcode.app
  name: Whipcode API Status
  themeUrl: https://av9.dev/whipcode/assets/status.css
  favicon: https://av9.dev/whipcode/assets/favicon.png

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

i18n:
  footer: ""
